### ISSUE TITLE
ETA for bridge-support in docker

### ISSUE THREAD

**Issue by yelodevopsi** [SoftEtherVPN/SoftetherVPN-docker#13]
Hi. I'm really in need of the bridge functionality for some VPN-clients. 🙏

Are there any howto/sources I could check in the meantime?

Anyhow, Thanks for a good product overall 👍

**Comment by chipitsine** [comment]
@weidi , can you help please ?

btw, what kind of bridge are we talking about, SE bridge ? or docker bridged network ?

**Comment by yelodevopsi** [comment]
> [@weidi](https://github.com/weidi) , can you help please ?
> 
> btw, what kind of bridge are we talking about, SE bridge ? or docker bridged network ?

I'm in need for a VPN-client bridge running `network_mode: host` .

The setup I'm trying to solve is to access the LAN behind the VPN-client connecting to a central VPN public server we have (Spoke and Hub configuration).

I haven't tested the softethervpn official docker image here yet. 
```yaml
  vpnclient:
    image: "containinger/docker-softether-vpn-client:latest"
    container_name: vpnclient
    hostname: vpnclient
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: "no"
    labels:
      service.name: "vpnclient"
    environment:
      SE_HUB: DEFAULT
      SE_SERVER: "vpn.my.central.server:5555"
      SE_USERNAME: myUsername
      SE_PASSWORD: <password>
```
