### ISSUE TITLE
Dynamic DNS problem

### ISSUE THREAD

**Issue by gLeW7** [SoftEtherVPN/SoftetherVPN-docker#15]
Hi, here's how I've configured my Softether VPN Server.

The problem I'm having is that every time I restart the Softether container, it generates a new current DDNS.

All the other settings remain the same, but the Dynamic DNS changes every time.

What could be causing this?

softether:
    container_name: softether
    image: softethervpn/vpnserver:stable
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
     - 444:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 8888:8888
      - 1701:1701/udp
      - 9821:9821
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./softether_data:/var/lib/softether
      - ./softether_log:/var/log/softether

**Comment by weidi** [comment]
Please try latest instead of stable. 
Currently the stable build is about 1 year old and will not use /var/lib and /var/log

**Comment by gLeW7** [comment]
Thanks for the response, i already change stable for lastest, an now i have the server version 

VPN Server>about
About command - Display the version information
SoftEther VPN Command Line Management Utility (vpncmd command)
Developer Edition
Version 5.02 Build 5187 (English)
Compiled 2025/03/31 06:16:34 by  at buildkitsandbox

But still have the same problem each time change the ddns Host name

Now i have thi config

softether:
    container_name: softether
    image: softethervpn/vpnserver:latest
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      #- 53:53
      - 444:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 8888:8888
      - 1701:1701/udp
      - 9821:9821
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./softether_server/softether_data:/mnt


Also when i try to run with port 53 giveme this error

docker compose up softether 
Attaching to softether
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint softether (cb2fdc4142574edd9727a7199416aac54f7jsl39lcjhbs25pxoq9du2co0mw6): failed to bind host port for 0.0.0.0:53:86.19.0.28:53/tcp: address already in use

i check and the port ist open, also i dont have any other container using port 53.

**Comment by weidi** [comment]
I assume port 53 is occupied by resolved but that port is for dns tunneling only what is needed only in rare cases.

Just to understand correctly you are referring to the https://softether.net/ ddns service or something you implemented yourself?
Can you try specifing the container_name in the composefile?

```yaml
version: '3'

services:
  softether:
    image: softethervpn/vpnserver:latest
    container_name: softethervpnserver
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - 443:443         #Management and HTTPS tunneling
      - 992:992         #HTTPS tunneling
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./softether_data:/var/lib/softether"
      - "./softether_log:/var/log/softether"

```
